### ISSUE TITLE
The username and password isnt working

### ISSUE THREAD

**Issue by Aneesha0912** [dingwei426/Recipe-Manager#1]
When  i set any username and password it says "The username was used ".I am not able to proceed further.

**Comment by dingwei426** [comment]
> When i set any username and password it says "The username was used ".I am not able to proceed further.

@Aneesha0912 
I think there is an issue with the database configuration. I have uploaded the sql script file to create mysql database scheme for this application. You may create a new user and connection and run the script using mysql workbench (if you are not familiar with mysql and it is easier to manage). Remember to change the database info, I have mentioned it in the updated README file. BTW, thanks for raising the issue!

**Comment by Aneesha0912** [comment]
I think it worked , thank you . I will get back to you if I face any other problems
